"""Pin the shipped brand kit — Zero, the Aegis Zero mascot.

``docs/brand/*.png`` are generated by ``scripts/make_brand.py`` from the
committed SVG masters; ``docs/brand/brand.assets.json`` pins them
byte-for-byte (``--check`` verifies them). Like the demo assets, the
rasters can never silently drift from what was reviewed.

Two tiers, mirroring ``test_demo_video.py``:

* **Everywhere** (no Pillow, no rsvg): the SVG masters parse, the
  manifest matches the shipped files' bytes and sha256s, and the
  script's ``--check`` mode passes against the shipped state.
* **When Pillow is installed**: pixel probes assert the art actually
  paints what ``docs/brand/BRAND.md`` says it paints — the shield-zero
  body, the dark zero-ring, the face, the gold verified-spark — and that
  the avatar survives round crops and favicon size. A renderer upgrade
  that changes rasterisation fails here on purpose: regenerate with
  ``python scripts/make_brand.py``.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
BRAND = REPO / "docs" / "brand"
MANIFEST = BRAND / "brand.assets.json"

MASTERS = ("zero-avatar.svg", "aegis-zero-lockup.svg", "og-card.svg", "endcard-lockup.svg")


def _load(name: str, path: Path):
    """Import a repo file by path (scripts/ is not a package)."""
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


make_brand = _load("make_brand", REPO / "scripts" / "make_brand.py")


def _manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


# ------------------------------------------------- everywhere (no deps)
def test_svg_masters_parse() -> None:
    for name in MASTERS:
        root = ET.parse(BRAND / name).getroot()
        assert root.tag.endswith("svg"), name
        assert "viewBox" in root.attrib, name


def test_mascot_geometry_is_identical_across_masters() -> None:
    """The composites inline the mascot (self-contained files) — so the
    shield-zero geometry must be identical in all four masters. Whitespace
    is normalised so indentation may differ, geometry may not."""
    ET.register_namespace("", "http://www.w3.org/2000/svg")
    avatar = ET.parse(BRAND / "zero-avatar.svg").getroot()
    shield = avatar.find(".//{*}path[@id='shield']")
    assert shield is not None, "zero-avatar.svg must define the shield path"
    norm = lambda s: " ".join(s.split())  # noqa: E731
    geometry = [
        norm(shield.attrib["d"]),
        # the zero-ring
        'cx="256" cy="238" r="84"',
        # the eyes
        'cx="224" cy="252" r="24"',
        'cx="288" cy="252" r="24"',
        # the smile
        norm("M 240 286 Q 256 300 272 286"),
        # the verified spark
        norm(
            "M 404 88 Q 408 104 424 110 Q 408 116 404 132 Q 400 116 384 110 Q 400 104 404 88 Z"
        ),
    ]
    for name in MASTERS[1:]:
        text = norm((BRAND / name).read_text(encoding="utf-8"))
        for g in geometry:
            assert g in text, f"{name} drifted from the avatar master: missing {g[:40]!r}"


def test_manifest_pins_shipped_binaries_byte_for_byte() -> None:
    files = _manifest()["files"]
    assert len(files) == 9, "avatar sizes x5 + favicon + three lockups/cards"
    for rel, pinned in files.items():
        path = REPO / rel
        assert path.is_file(), rel
        data = path.read_bytes()
        assert len(data) == pinned["bytes"], rel
        assert hashlib.sha256(data).hexdigest() == pinned["sha256"], rel
        assert pinned["width"] * pinned["height"] > 0, rel


def test_avatar_is_pinned_at_every_social_size() -> None:
    files = _manifest()["files"]
    for size in (512, 256, 128, 64, 32):
        assert f"docs/brand/zero-avatar-{size}.png" in files
    assert files["docs/brand/zero-avatar-512.png"]["width"] == 512
    assert files["docs/brand/favicon.ico"]["width"] == 48  # largest packed size
    assert files["docs/brand/og-card.png"]["width"] == 1200
    assert files["docs/brand/og-card.png"]["height"] == 630


def test_check_mode_passes_against_the_shipped_state(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert make_brand.check() == 0
    assert "match the manifest" in capsys.readouterr().out


# ----------------------------------------------------- when Pillow exists
requires_pil = pytest.mark.skipif(make_brand.Image is None, reason="Pillow not installed")


@requires_pil
def test_avatar_paints_the_shield_zero_story() -> None:
    from PIL import Image

    with Image.open(BRAND / "zero-avatar-512.png") as im:
        rgb = im.convert("RGBA")

    def px(x: int, y: int) -> tuple[int, int, int, int]:
        return rgb.getpixel((x, y))

    r, g, b, a = px(256, 238)  # shield body between the eyes
    assert a == 255 and g > 190 and 140 < b < 220 and r < 60
    r, g, b, _ = px(256, 154)  # the zero-ring, dark on the bright body
    assert r < 40 and g < 110
    r, g, b, _ = px(224, 252)  # left eye (kawaii-size, below the midline)
    assert r < 40 and g < 90
    r, g, b, _ = px(217, 244)  # eye glint
    assert r > 230 and g > 230 and b > 230
    r, g, b, _ = px(256, 293)  # the smile
    assert r < 40 and g < 90
    r, g, b, _ = px(404, 110)  # the verified spark
    assert r > 230 and 170 < g < 235 and b < 60
    r, g, b, _ = px(256, 420)  # the gold tip light
    assert r > 230 and 170 < g < 235 and b < 60
    r, g, b, _ = px(256, 26)  # the top orbit dot
    assert r > 200 and 160 < g < 235 and b < 80
    r, g, b, a = px(256, 8)  # deep field, inside the plate
    assert a == 255 and r < 30 and g < 60


@requires_pil
def test_avatar_survives_round_crops() -> None:
    from PIL import Image

    with Image.open(BRAND / "zero-avatar-512.png") as im:
        rgba = im.convert("RGBA")
    assert rgba.getpixel((0, 0))[3] == 0, "corners must be transparent"
    worst = 0.0
    for y in range(0, 512, 2):  # stride 2: fast, still exhaustive enough
        for x in range(0, 512, 2):
            if rgba.getpixel((x, y))[3] > 8:
                worst = max(worst, math.hypot(x - 256, y - 256))
    assert worst < 251, f"art escapes the round crop (max radius {worst:.1f})"


@requires_pil
def test_face_survives_favicon_size() -> None:
    from PIL import Image

    with Image.open(BRAND / "zero-avatar-64.png") as im:
        rgb = im.convert("RGB")
    body = rgb.getpixel((32, 34))
    assert body[1] > 170, "shield body must stay bright at 64px"
    eye_x, eye_y = round(224 * 64 / 512), round(252 * 64 / 512)
    region = [
        rgb.getpixel((x, y))
        for x in range(max(0, eye_x - 3), eye_x + 4)
        for y in range(max(0, eye_y - 3), eye_y + 4)
    ]
    darkest = min(region, key=lambda p: sum(p))
    assert sum(darkest) < sum(body) - 180, "the eyes must still read at 64px"


@requires_pil
def test_lockups_and_card_paint_their_scenes() -> None:
    from PIL import Image

    def lit(path: Path, box: tuple[int, int, int, int], pred) -> int:
        with Image.open(path) as im:
            rgb = im.convert("RGB")
        x0, y0, x1, y1 = box
        return sum(
            1 for y in range(y0, y1) for x in range(x0, x1) if pred(rgb.getpixel((x, y)))
        )

    white = lambda p: p[0] > 230 and p[1] > 230 and p[2] > 230  # noqa: E731
    teal = lambda p: p[1] > 170 and p[2] > 120 and p[0] < 120  # noqa: E731

    # end card: mascot + wordmark on pure black, ready for make_video
    with Image.open(BRAND / "endcard-lockup.png") as im:
        assert im.convert("RGB").getpixel((5, 5)) == (0, 0, 0)
    assert lit(BRAND / "endcard-lockup.png", (400, 430, 800, 515), white) > 3000
    assert lit(BRAND / "endcard-lockup.png", (400, 540, 800, 570), teal) > 100
    # shield body above the face: bright teal below the ring, above the eyes
    assert lit(BRAND / "endcard-lockup.png", (560, 195, 640, 215), teal) > 1500

    # og card: 1200x630, mascot left, wordmark + promise right
    assert lit(BRAND / "og-card.png", (600, 180, 980, 255), white) > 3000
    assert lit(BRAND / "og-card.png", (600, 280, 780, 310), teal) > 100
    assert lit(BRAND / "og-card.png", (600, 350, 1100, 440), lambda p: p[0] > 150) > 1500

    # horizontal lockup: mascot beside the wordmark on a dark plate
    assert lit(BRAND / "aegis-zero-lockup.png", (430, 120, 760, 210), white) > 3000
    assert lit(BRAND / "aegis-zero-lockup.png", (430, 230, 640, 260), teal) > 100


@requires_pil
def test_favicon_packs_three_sizes() -> None:
    from PIL import Image

    with Image.open(BRAND / "favicon.ico") as im:
        assert im.size == (48, 48)
        assert im.info.get("sizes") == {(16, 16), (32, 32), (48, 48)}
