"""Pin the shipped video assets to the same timeline as the cast and SVG.

``docs/demo.mp4``, ``docs/demo.gif`` and ``docs/demo-poster.png`` are
generated by ``scripts/make_video.py`` from the SAME pinned transcript and
schedule as ``docs/demo.cast`` / ``docs/demo.svg``; ``docs/demo.video.json``
pins the shipped binaries byte-for-byte (``--check`` verifies them).

The tests come in two tiers:

* **Everywhere** (no Pillow, no ffmpeg): the manifest matches the shipped
  files' sizes and sha256s, and its timeline is byte-identical to the cast
  event times — the video cannot disagree with the other two assets.
* **When Pillow is installed**: probe frames rendered in-memory must paint
  the demo story (typing, DENY/SANITIZE verdicts in their palette colours,
  blinking closing cursor, end card with logo and install chip), and the
  poster must equal the rendered frame exactly. A Pillow/freetype upgrade
  that changes glyph rasterisation will fail here on purpose: regenerate
  with ``python scripts/make_video.py``.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]


def _load(name: str, path: Path):
    """Import a repo file by path (examples/ and scripts/ are not packages)."""
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


make_video = _load("make_video", REPO / "scripts" / "make_video.py")
make_demo = sys.modules["make_demo"]  # loaded by make_video
demo = sys.modules["demo"]  # loaded by make_demo

MANIFEST_PATH = REPO / "docs" / "demo.video.json"
MP4_PATH = REPO / "docs" / "demo.mp4"


def _manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


# ------------------------------------------------- everywhere (no deps)
def test_manifest_pins_the_shipped_binaries_byte_for_byte():
    manifest = _manifest()
    assert set(manifest["files"]) == {"docs/demo.mp4", "docs/demo.gif", "docs/demo-poster.png"}
    for rel, entry in manifest["files"].items():
        path = REPO / rel
        assert path.is_file(), f"{rel} is missing"
        assert path.stat().st_size == entry["bytes"], f"{rel} size drifted"
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        assert digest == entry["sha256"], f"{rel} content drifted — regenerate"


def test_video_plays_exactly_the_cast_timeline():
    manifest = _manifest()
    timed, duration = make_demo.schedule(demo.transcript())
    cast_times = [
        json.loads(line)[0]
        for line in (REPO / "docs" / "demo.cast").read_text(encoding="utf-8").splitlines()[1:]
    ]
    assert make_video.LINE_TIMES == cast_times == [time for _, time in timed]
    assert manifest["line_times"] == cast_times  # cast == SVG == video, always
    assert manifest["duration"]["terminal"] == duration
    total = round(duration + make_video.CROSSFADE + make_video.ENDCARD, 2)
    assert manifest["duration"]["total"] == total
    assert 25 <= duration < 32  # the "30-second demo" promise holds on video
    assert 32 <= total < 36  # …plus a short end card, still a tight socials cut
    frame = manifest["frame"]
    assert (frame["width"], frame["height"]) == (1920, 1080)
    assert frame["width"] % 2 == 0 and frame["height"] % 2 == 0  # player-safe
    assert frame["fps"] == 30
    assert frame["frames"] == round(total * frame["fps"])


def test_check_mode_detects_drift_and_passes_when_in_sync(monkeypatch, capsys):
    monkeypatch.setattr(make_video, "_sha256", lambda path: "0" * 64)
    assert make_video.main(["--check"]) == 1
    assert "drifted: docs/demo.mp4" in capsys.readouterr().out

    monkeypatch.undo()
    assert make_video.main(["--check"]) == 0
    assert "video assets in sync" in capsys.readouterr().out


# --------------------------------------------- Pillow-gated probe frames
requires_pil = pytest.mark.skipif(make_video.Image is None, reason="Pillow not installed")


def _hex(color: str) -> tuple[int, int, int]:
    value = color.lstrip("#")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def _count_near(
    im, rgb: tuple[int, int, int], box: tuple[int, int, int, int], tol: int = 60
) -> int:
    """Pixels inside ``box`` within ``tol`` per channel of ``rgb``."""
    pixels = im.load()
    x0, y0, x1, y1 = box
    return sum(
        1
        for y in range(y0, y1)
        for x in range(x0, x1)
        if all(
            abs(channel - target) <= tol
            for channel, target in zip(pixels[x, y][:3], rgb, strict=True)
        )
    )


def _row_box(res, row: int) -> tuple[int, int, int, int]:
    x0 = res.win_x + 10
    x1 = res.win_x + make_video.WINDOW_W - 10
    return x0, res.baseline(row) - res.ascent, x1, res.baseline(row) + res.descent


@requires_pil
def test_probe_frames_paint_the_pinned_story():
    res = make_video._resources()
    chrome_bg = _hex(make_video.CHROME_BG)

    # Before the first line: only chrome, no ink anywhere in the text area.
    empty = make_video.render_frame(0.2)
    for row in (0, 2, 6):
        assert _count_near(empty, chrome_bg, _row_box(res, row), tol=0) > 2000
        assert _count_near(empty, _hex(make_video.FG["deny"]), _row_box(res, row)) == 0

    # The command line types itself inside its pinned delay window.
    typing = make_video.render_frame(2.5)
    box = _row_box(res, 2)
    ink_x_max = max(
        x
        for y in range(box[1], box[3])
        for x in range(box[0], box[2])
        if typing.load()[x, y][:3] != chrome_bg
    )
    cmd = next(line for line in res.lines if line["kind"] == "cmd")
    cursor_x = cmd["x"] + int(1 + cmd["prompt_w"]) + res.type_x[11]
    assert cursor_x - 6 <= ink_x_max <= cursor_x + int(res.advance) + 2  # 11 chars + cursor
    done = make_video.render_frame(3.2)
    assert _count_near(done, _hex(make_video.FG["cmd"]), _row_box(res, 2)) > 150

    # Policy verdicts land in their rows, in their palette colours.
    verdicts = make_video.render_frame(16.0)
    assert _count_near(verdicts, _hex(make_video.FG["deny"]), _row_box(res, 6)) > 300
    assert _count_near(verdicts, _hex(make_video.FG["deny"]), _row_box(res, 8)) > 300
    assert _count_near(verdicts, _hex(make_video.FG["deny"]), _row_box(res, 10)) > 300
    assert _count_near(verdicts, _hex(make_video.FG["warn"]), _row_box(res, 12)) > 300
    assert _count_near(verdicts, _hex(make_video.FG["deny"]), _row_box(res, 6)) > _count_near(
        verdicts, _hex(make_video.FG["ok"]), _row_box(res, 6)
    )

    # The engine run answers, audits and stats.
    finished = make_video.render_frame(make_video.POSTER_T)
    assert _count_near(finished, _hex(make_video.FG["ok"]), _row_box(res, 16)) > 300
    assert _count_near(finished, _hex(make_video.FG["dim"]), _row_box(res, 19)) > 300

    # The closing prompt blinks: cursor ON at the poster time, OFF a half-
    # blink later. (The closing prompt is the row AFTER the transcript.)
    closing_row = make_video.ROWS - 1
    cursor_box = (
        res.closing["x"],
        res.baseline(closing_row) - 27,
        res.closing["x"] + int(2 * res.advance),
        res.baseline(closing_row),
    )
    assert _count_near(finished, _hex(make_video.INK), cursor_box, tol=40) > 50
    later = make_video.render_frame(make_video.POSTER_T + 0.6)
    assert _count_near(later, _hex(make_video.INK), cursor_box, tol=40) == 0

    # End card: pure black, real logo (cyan + gold), install chip, centred.
    card = make_video.render_frame(32.0).load()
    assert card[30, 30][:3] == (0, 0, 0)
    logo, lx, ly = res.endcard["logo"]
    logo_box = (lx, ly, lx + logo.width, ly + logo.height)
    cyan_count = _count_near(
        make_video.render_frame(32.0), _hex(make_video.BRAND_CYAN), logo_box, tol=70
    )
    gold_count = _count_near(make_video.render_frame(32.0), (255, 215, 0), logo_box, tol=80)
    assert cyan_count > 400
    assert gold_count > 20
    chip, cx, cy = res.endcard["chip"]
    assert abs(cx + chip.width / 2 - 960) <= 4
    assert (
        _count_near(
            make_video.render_frame(32.0),
            _hex(make_video.PROMPT_GREEN),
            (cx, cy, cx + chip.width // 3, cy + chip.height),
            tol=70,
        )
        > 30
    )


@requires_pil
def test_poster_is_exactly_the_rendered_frame():
    from PIL import Image, ImageChops, ImageStat

    poster = Image.open(REPO / "docs" / "demo-poster.png").convert("RGB")
    reference = make_video.render_frame(make_video.POSTER_T)
    assert poster.size == reference.size == (1920, 1080)
    difference = ImageChops.difference(poster, reference)
    assert sum(ImageStat.Stat(difference).mean) == 0.0  # byte-faithful render


# ------------------------------------------------- ffprobe-gated checks
requires_ffprobe = pytest.mark.skipif(
    shutil.which("ffprobe") is None, reason="ffprobe not installed"
)


@requires_ffprobe
def test_shipped_mp4_is_player_compatible():
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_streams",
            "-of",
            "json",
            str(MP4_PATH),
        ],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
        timeout=60,
    )
    stream = json.loads(result.stdout)["streams"][0]
    assert stream["codec_name"] == "h264"
    assert stream["pix_fmt"] == "yuv420p"  # every browser/phone plays this
    assert (stream["width"], stream["height"]) == (1920, 1080)
    assert stream["r_frame_rate"] == "30/1"
    manifest = _manifest()
    assert abs(float(stream["duration"]) - manifest["duration"]["total"]) < 0.2
    assert int(stream["nb_frames"]) == manifest["frame"]["frames"]
