"""Pin the shipped demo assets to the live code that produces them.

``docs/demo.svg`` (the animated 30-second README demo) and ``docs/demo.cast``
(the asciinema recording) are *generated* by ``scripts/make_demo.py`` from the
transcript of a real ``examples/demo.py`` engine run. These tests fail the
build if anyone edits the artifacts by hand, changes the demo without
regenerating, or breaks a promise the README makes about it: offline,
deterministic, ~30 seconds, reproducible with one command.
"""

from __future__ import annotations

import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

import aegis_zero

REPO = Path(__file__).resolve().parents[1]


def _load(name: str, path: Path):
    """Import a repo file by path (examples/ and scripts/ are not packages)."""
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


make_demo = _load("make_demo", REPO / "scripts" / "make_demo.py")
demo = sys.modules["demo"]  # loaded by make_demo

TRANSCRIPT = demo.transcript()
CAST_PATH = REPO / "docs" / "demo.cast"
SVG_PATH = REPO / "docs" / "demo.svg"


def test_transcript_is_deterministic_and_keeps_its_promises():
    again = demo.transcript()
    assert again == TRANSCRIPT  # byte-identical on every run: no network, no clock

    text = "\n".join(line for _, line in TRANSCRIPT)
    assert text.count("DENY") == 3  # SSRF probe, credential read, rm -rf /
    assert "SANITIZE" in text  # bearer token redaction
    assert "The answer is 42." in text
    assert "audit: pass" in text
    assert f"Aegis Zero v{aegis_zero.__version__}" in text
    assert "no model server, no network" in text


def test_committed_cast_is_current_and_wellformed():
    committed = CAST_PATH.read_text(encoding="utf-8")
    assert committed == make_demo.render_cast(TRANSCRIPT)  # no hand edits / drift

    lines = committed.splitlines()
    header = json.loads(lines[0])
    assert header["version"] == 2
    assert header["width"] == 80
    assert header["height"] == len(TRANSCRIPT) + 2
    assert 25 <= header["duration"] < 32  # the "30-second demo" promise

    events = [json.loads(line) for line in lines[1:]]
    assert len(events) == len(TRANSCRIPT)
    times = [event[0] for event in events]
    assert times == sorted(times)  # player-friendly: never backwards
    for event, (_, body) in zip(events, TRANSCRIPT, strict=True):
        assert event[1] == "o"
        assert event[2] == body + "\n"


def test_committed_svg_is_current_animated_and_accessible():
    committed = SVG_PATH.read_text(encoding="utf-8")
    assert committed == make_demo.render_svg(TRANSCRIPT)  # no hand edits / drift

    assert "GENERATED by scripts/make_demo.py" in committed  # do-not-edit marker
    for needle in ("aegis-in", "aegis-blink", "prefers-reduced-motion"):
        assert needle in committed  # animation + reduced-motion fallback
    assert committed.count('class="ln"') == 19  # 18 transcript lines + closing prompt
    assert f"v{aegis_zero.__version__}" in committed
    # The renderer swaps spaces for no-break spaces so runs never collapse.
    for needle in ("DENY", "SANITIZE", "The answer is 42.", "audit: pass"):
        assert needle.replace(" ", "\u00a0") in committed


def test_cast_and_svg_play_the_same_timeline():
    timed, duration = make_demo.schedule(TRANSCRIPT)
    assert duration < 32  # both media finish inside the 30-second window

    cast_times = [json.loads(line)[0] for line in CAST_PATH.read_text().splitlines()[1:]]
    assert cast_times == [time for _, time in timed]

    # One delay per visible line, plus the closing prompt (no sp lines, no
    # cursor: its style is "delay,delay" and does not match the regex).
    svg_delays = [
        float(d) for d in re.findall(r'animation-delay:([0-9.]+)s"', SVG_PATH.read_text())
    ]
    visible = [time for (kind, _), time in timed if kind != "sp"]
    assert svg_delays == [*visible, timed[-1][1]]


def test_demo_script_reproduces_the_transcript_byte_for_byte():
    result = subprocess.run(
        [sys.executable, "examples/demo.py"],
        cwd=REPO,
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=120,
        env={"PYTHONIOENCODING": "utf-8", "PATH": "/usr/bin:/bin"},
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout == "\n".join(line for _, line in TRANSCRIPT) + "\n"


def test_check_flag_reports_drift_and_passes_when_in_sync(monkeypatch, capsys):
    monkeypatch.setattr(make_demo, "transcript", lambda: TRANSCRIPT)
    real_svg = make_demo.render_svg

    monkeypatch.setattr(make_demo, "render_svg", lambda lines: "drifted")
    assert make_demo.main(["--check"]) == 1
    assert "drifted: docs/demo.svg" in capsys.readouterr().out

    monkeypatch.setattr(make_demo, "render_svg", real_svg)
    assert make_demo.main(["--check"]) == 0
    assert "in sync" in capsys.readouterr().out
